# Generated by Django 3.2.10 on 2024-06-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
