# Generated by Django 3.2.10 on 2024-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0004_auto_20240603_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
