# Generated by Django 3.2.10 on 2024-06-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0005_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
