# Generated by Django 3.2.10 on 2024-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0006_remove_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleCategory', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
