# Generated by Django 3.2.10 on 2024-06-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0008_vehiclebrand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleCategories',
        ),
    ]
