# Generated by Django 3.2.10 on 2024-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0009_auto_20240604_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
