# Generated by Django 3.2.10 on 2024-06-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0011_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='partscategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_Cat', models.CharField(max_length=100, null=True)),
                ('v_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.brands')),
                ('v_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.vehiclecategories')),
            ],
        ),
    ]
