# Generated by Django 3.2.10 on 2024-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0012_partscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partscategory',
            name='part_image',
            field=models.ImageField(blank=True, null=True, upload_to='part_images/'),
        ),
    ]
