# Generated by Django 3.2.10 on 2024-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0013_partscategory_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partscategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
