# Generated by Django 3.2.10 on 2024-06-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0016_auto_20240605_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partscategory',
            name='Parts_Categories',
        ),
        migrations.AddField(
            model_name='partscategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='part_image',
            field=models.ImageField(blank=True, null=True, upload_to='part_images/'),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='parts_Cat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='v_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spares.brands'),
        ),
        migrations.AddField(
            model_name='partscategory',
            name='v_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spares.vehiclecategories'),
        ),
    ]
