# Generated by Django 3.2.10 on 2024-06-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0017_auto_20240605_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
