# Generated by Django 3.2.10 on 2024-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0018_top_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='is_car',
            field=models.BooleanField(default=True),
        ),
    ]
