# Generated by Django 3.2.10 on 2024-06-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0019_brands_is_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partscategory',
            name='parts_Cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spares.top_categories'),
        ),
    ]
