# Generated by Django 3.2.10 on 2024-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0020_alter_partscategory_parts_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='partscategory',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
