# Generated by Django 3.2.10 on 2024-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0021_partscategory_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='partscategory',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
