# Generated by Django 3.2.10 on 2024-06-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0022_partscategory_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='partscategory',
            name='parts_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
